DROP TABLE IF EXISTS PeerMark;
DROP TABLE IF EXISTS StudentModList;
DROP TABLE IF EXISTS Groups;
DROP TABLE IF EXISTS Student;
DROP TABLE IF EXISTS Modules;


CREATE TABLE Student (
		SID INT NOT NULL,
		fullName VARCHAR(255) NOT NULL,
		CONSTRAINT pk_student PRIMARY KEY (studentID)
) ENGINE = InnoDB;

CREATE TABLE Modules (
		MCode VARCHAR(6) NOT NULL,
		CONSTRAINT pk_modules PRIMARY KEY (MCode)
) ENGINE = InnoDB;

CREATE TABLE StudentModList (
		SID INT NOT NULL,
		MCode VARCHAR(6) NOT NULL,
		CONSTRAINT pk_studentmodlist PRIMARY KEY (SID, MCode),
		CONSTRAINT fk_studmod_stud FOREIGN KEY (SID) REFERENCES Student (SID),
		CONSTRAINT fk_studmod_mod FOREIGN KEY (MCode) REFERENCES Modules (MCode)
) ENGINE = InnoDB;

CREATE TABLE Groups (
		GName VARCHAR(10) NOT NULL,
		GMark INT NOT NULL,
		MCode VARCHAR(6) NOT NULL,
		CONSTRAINT pk_grps PRIMARY KEY (GName),
		CONSTRAINT fk_grps_mod FOREIGN KEY (MCode) REFERENCES Modules (MCode),
) ENGINE = InnoDB;

CREATE TABLE PeerMark (
		PID INT NOT NULL AUTO_INCREMENT,
		SID1 INT NOT NULL,
		SID2 INT NOT NULL,
		PResearch INT NOT NULL,
		PCreative INT NOT NULL,
		PCooperation INT NOT NULL,
		PCommunication INT NOT NULL,
		PQuality INT NOT NULL,
		PAttendance INT NOT NULL,
		GName VARCHAR(10) NOT NULL,
		PComment VARCHAR(1000) NOT NULL,

		CONSTRAINT pk_peermark PRIMARY KEY (PID),
		CONSTRAINT fk_pmrk_grp FOREIGN KEY (GName) REFERENCES Groups (GName),
		CONSTRAINT fk_pmrk_stud1 FOREIGN KEY (SID1) REFERENCES Student (SID),
		CONSTRAINT fk_pmrk_stud2 FOREIGN KEY (SID2) REFERENCES Student (SID)
) ENGINE = InnoDB;
